import { SupportedFormat } from '../types';

export const SUPPORTED_FORMATS: SupportedFormat[] = [
  {
    extension: 'JPG / JPEG',
    mimeType: 'image/jpeg',
    name: 'JPEG Image',
    category: 'Image',
    readMetadata: true,
    editMetadata: true,
    removeMetadata: true,
    status: 'supported',
    description: 'Most common photograph format. Stores rich EXIF, GPS coordinates, camera hardware serials, timestamps, and IPTC/XMP tags.',
    typicalRisks: ['Physical GPS coordinates', 'Device serial numbers', 'Creation timestamps', 'Photographer identity', 'Camera settings'],
  },
  {
    extension: 'PNG',
    mimeType: 'image/png',
    name: 'Portable Network Graphics',
    category: 'Image',
    readMetadata: true,
    editMetadata: 'Partial',
    removeMetadata: true,
    status: 'supported',
    description: 'Supports ancillary chunk metadata including tEXt, zTXt, iTXt (Author, Software, Comments), eXIf chunks, and creation timestamps.',
    typicalRisks: ['Author comments', 'Application fingerprints', 'Embedded color profiles', 'Modification dates'],
  },
  {
    extension: 'WebP',
    mimeType: 'image/webp',
    name: 'WebP Image',
    category: 'Image',
    readMetadata: true,
    editMetadata: 'Partial',
    removeMetadata: true,
    status: 'supported',
    description: 'Modern compressed web image container. Can encapsulate EXIF and XMP metadata chunks.',
    typicalRisks: ['EXIF hardware profile', 'GPS tags (if converted from JPEG)', 'Author credits'],
  },
  {
    extension: 'PDF',
    mimeType: 'application/pdf',
    name: 'Portable Document Format',
    category: 'Document',
    readMetadata: true,
    editMetadata: true,
    removeMetadata: true,
    status: 'supported',
    description: 'Documents retain Author, Creator, Producer software, Subject, Keywords, and exact creation/edit timestamps.',
    typicalRisks: ['User login/author names', 'Company or department tags', 'Software build versions', 'Document revision dates'],
  },
  {
    extension: 'DOCX / XLSX / PPTX',
    mimeType: 'application/vnd.openxmlformats-officedocument',
    name: 'Microsoft Office OpenXML',
    category: 'Document',
    readMetadata: false,
    editMetadata: false,
    removeMetadata: false,
    status: 'planned',
    description: 'Contains core.xml, app.xml, and custom.xml detailing company name, last editor, revision numbers, and total edit time.',
    typicalRisks: ['Last modified user', 'Organization name', 'Hidden revision histories', 'Printer profiles'],
  },
  {
    extension: 'MP3 / WAV',
    mimeType: 'audio/mpeg',
    name: 'Audio Recordings & Music',
    category: 'Media',
    readMetadata: false,
    editMetadata: false,
    removeMetadata: false,
    status: 'planned',
    description: 'ID3v1 and ID3v2 tags store artist names, album titles, recording software, encoder settings, and embedded comments.',
    typicalRisks: ['Artist identity', 'Encoder application signatures', 'Recording location comments'],
  },
  {
    extension: 'MP4 / MOV',
    mimeType: 'video/mp4',
    name: 'QuickTime / MPEG-4 Video',
    category: 'Media',
    readMetadata: false,
    editMetadata: false,
    removeMetadata: false,
    status: 'planned',
    description: 'QuickTime atom moov/udta tags frequently contain mobile phone GPS tracks, device hardware models, and capture times.',
    typicalRisks: ['GPS travel trajectories', 'Phone model and iOS/Android build', 'Recording time'],
  },
];
